### ISSUE TITLE
Dotenv file parameter type

### ISSUE THREAD

**Issue by jahvon** [flowexec/flow#247]
Add support for loading environment variables from dotenv (.env) files as a new parameter type in executable configurations. This would extend the existing `params` system to include `envFile` alongside `text`, `secretRef`, and `prompt`.

### New Parameter Type: envFile
```yaml
executables:
  - name: start-server
    exec:
      params:
        - envFile: .env
        - secretRef: api-key
          envKey: API_KEY
        - text: "development"
          envKey: NODE_ENV
      cmd: npm start
```

### Parameter Type Definition
```yaml
params:
  - envFile: path/to/file.env    # Load all variables from file
  # OR with explicit envKey mapping
  - envFile: .env
     envKey: DATABASE_URL         # Load only DATABASE_URL from .env
```
